package globalgamejam.game;

public enum EffectEnum {

	INVERSE_SCREEN,
	SCORE_FREEZE,
	MUSIC_MULTIPLICATOR_J1,
	MUSIC_MULTIPLICATOR_J2,
	INVERSE_COMMAND_J1,
	INVERSE_COMMAND_J2,
	HEAVY_J1,
	HEAVY_J2
}
